name: CustomStructures
version: 1.7.1
main: com.ryandw11.structure.CustomStructures
author: Ryandw11
description: A plugin which allows you to spawn in custom structures!
depend: [WorldEdit]
softdepend: [MythicMobs, Citizens]
api-version: 1.13
commands:
    customstructure:
     description: Main command.
     aliases: [cs, cstructure, customs, cws, cstruct]